### ISSUE TITLE
Minor Bug in DrawingInTheAir Example

### ISSUE THREAD

**Issue by vigneshjathavara** [01org/Intel-Pattern-Matching-Technology#10]
In function readVectorFromIMU()

Button HIGH and LOW have to be interchanged in the while loops

/* Wait until button is pressed */
while (digitalRead(buttonPin) == HIGH); -----> while (digitalRead(buttonPin) == LOW);

 /* While button is being held... */
    while (digitalRead(buttonPin) == LOW)  -------->  while (digitalRead(buttonPin) == HIGH) 

This has to be done so that there is a wait until button is pressed

**Comment by eriknyquist** [comment]
Thanks @vigneshjathavara, this was because I repurposed the soft-reset button on Arduino 101 for testing this example (saves me hooking up a button), and that's how it is connected. But, you're right, most people won't connect a button in this way.

**Comment by eriknyquist** [comment]
Fixed in PR https://github.com/01org/Intel-Pattern-Matching-Technology/pull/11
