### ISSUE TITLE
Provide a README.md for each Example

### ISSUE THREAD

**Issue by jerroydmoore** [01org/Intel-Pattern-Matching-Technology#14]
Context and examples of input/input in each example would be greatly appreciated.

**Comment by eriknyquist** [comment]
@jerroydmoore should have some in the next week

**Comment by eriknyquist** [comment]
Hey, sorry about the long delay, but we have some better docs now; an API reference https://github.com/01org/Intel-Pattern-Matching-Technology/blob/master/README.md|

and a development tutorial https://github.com/01org/Intel-Pattern-Matching-Technology/blob/master/examples/DrawingInTheAir/README.md

It's not exactly what you were looking for-- a README for each example-- but I think the tutorial, which is quite detailed, is going to serve the same purpose.

**Comment by jerroydmoore** [comment]
Thanks!
