### ISSUE TITLE
Set GCR does not change GCR

### ISSUE THREAD

**Issue by marcusobrien** [01org/Intel-Pattern-Matching-Technology#17]
Hi,

The global context is always set at 127, you can not change it, even when calling the setGlobalContext function. Doesnt matter if in KNN or RBF mode.

Marcus

**Comment by eriknyquist** [comment]
Hi @marcusobrien, can you prove it with some code?

**Comment by marcusobrien** [comment]
Hi,

Yes, here is some  code and output 👍 

void setGContext(int gc)
{
	CuriePME.setGlobalContext(gc); 
	uint16_t newGC = CuriePME.getGlobalContext();
	if (newGC != gc)
	{
		Serial.print("Failed to ");
	}
	Serial.print("set Global Context to:");
	Serial.println(gc);
	Serial.print("Global context is Currently:");
	Serial.println(newGC);
}

void NNInfo()
{
	int neuronsCommitted = CuriePME.getCommittedCount();
	int neuronsAvailable = Intel_PMT::MaxNeurons;
	int neuronSize = Intel_PMT::MaxVectorSize;

	Serial.print("Neuron size="); Serial.println(neuronSize);
	Serial.print("Neurons available="); Serial.println(neuronsAvailable);
	Serial.print("Neurons committed="); Serial.println(neuronsCommitted);
	Serial.print("Global Context="); Serial.println(CuriePME.getGlobalContext());
//	Serial.print("Training Images="); Serial.println(numberImagesToTrain);
//	Serial.print("OCR Types of image to learn from file:"); Serial.println(numberOCRImageTypesToLearn);
//	Serial.print("Number of images to test :"); Serial.println(NUM_TO_TEST);
//	Serial.print("Testing for only known cats ");

//	if (RESTRICT_TESTING_TO_KNOWN_CATS)
//		Serial.println("enabled");
//	else
//		Serial.println("disabled");
		

	if (CuriePME.getClassifierMode() == Intel_PMT::PATTERN_MATCHING_CLASSIFICATION_MODE::RBF_Mode)
	{
		Serial.println("Mode is set to RBF");
	}
	else
	{
		Serial.println("Mode is set to KNN");
	}

//	printDistanceMode();
	
	//Serial.print("Known categories:");

	//whatCatsDoesNNKnow();

	//for (int i = 0; (i < NUM_IMAGES_TYPES && knownCats[i] != 0); i++)
	//{
	//	Serial.print(knownCats[i]);
	//	if ((i < (NUM_IMAGES_TYPES-1)) && knownCats[i+1] > 0)
	//		Serial.print(", ");
	//	else
	//		Serial.println("\n\n");
	//}
}

void setup()
{
//	numberOCRImageTypesToLearn = constrain(numberOCRImageTypesToLearn, 0, //NUM_IMAGES_TYPES);
	//numberImagesToTrain = constrain(numberImagesToTrain, 0, //MAX_NUM_IMAGES_TO_LEARN_EVER);

	//pinMode(chipSelect, OUTPUT);
	//digitalWrite(chipSelect, HIGH);

	Serial.begin(SerialBAUD);

	while (!Serial);
	
	delay(1000);
	
	CuriePME.begin();

	//CuriePME.begin(50, Intel_PMT::PATTERN_MATCHING_DISTANCE_MODE::L1_Distance,
		Intel_PMT::PATTERN_MATCHING_CLASSIFICATION_MODE::KNN_Mode,
		2, 20000);
	
	SD.begin(chipSelect);

	//setNNOptions();
}

void loop()
{
setGContext(1);
NNInfo();
}


OUTPUT 👍 

Toggling the Distance Mode
Current Distance mode is LSUP
Set the NN to L1 Distance
Current Distance mode is LSUP

Neuron size=128
Neurons available=128
Neurons committed=0
Global Context=127
Mode is set to RBF
Current Distance mode is LSUP


Marcus

**Comment by eriknyquist** [comment]
Fixed here https://github.com/01org/Intel-Pattern-Matching-Technology/pull/20

**Comment by marcusobrien** [comment]
Cool, thanks Eric !!

**Comment by marcusobrien** [comment]
Verified fixed. Can now set global context as expected.
