### ISSUE TITLE
Add constants for valid context range

### ISSUE THREAD

**Issue by marcusobrien** [01org/Intel-Pattern-Matching-Technology#18]
can we have some either static const for valid context range (so I dont have to change my source if this changes in the firmware), or #defines (no type checking but pre-processor values so smaller program size).

//Should be inside the Intel header files
static const uint16_t MAX_CONTEXT = 127;
static const uint16_t MIN_CONTEXT = 1;

Or better still an inline with a constraint so their is no exception/error - just carry on with the program by forcing it valid

void alignContext()
{
  NNContext = constrain(NNContext, MIN_CONTEXT, MAX_CONTEXT);
}

Thanks.

Marcus.

**Comment by eriknyquist** [comment]
Done https://github.com/01org/Intel-Pattern-Matching-Technology/pull/22

**Comment by marcusobrien** [comment]
Is the min context supposed to be 0 or 1 ? according to CuriePME.cpp line 276 above the func 

// valid range is 1-127
void Intel_PMT::setGlobalContext(uint16_t context)
{
	uint16_t gcrMask = ~GCR_GLOBAL & regRead16(GCR);
	gcrMask |= (context & GCR_GLOBAL);
	regWrite16(GCR, gcrMask);
}

So can you either change the constant or the comment please.

**Comment by eriknyquist** [comment]
Ah yes, I forgot to clarify that detail. I've fixed it here https://github.com/01org/Intel-Pattern-Matching-Technology/pull/24
