### ISSUE TITLE
Change Distance Mode - No effect

### ISSUE THREAD

**Issue by marcusobrien** [01org/Intel-Pattern-Matching-Technology#19]
Hi,

I wrote a toggle function to switch distance modes, it has no effect, the model remains in the state it is in when intialised, in my case LSUP 👍 

void printDistanceMode()
{
	if (CuriePME.getDistanceMode() == Intel_PMT::PATTERN_MATCHING_DISTANCE_MODE::L1_Distance)
	{
		Serial.println("Current Distance mode is L1");
	}
	else
	{
		Serial.println("Current Distance mode is LSUP");
	}
}

void toggleDistanceMode()
{
	printDistanceMode();

	if (CuriePME.getDistanceMode() == Intel_PMT::PATTERN_MATCHING_DISTANCE_MODE::L1_Distance)
	{
		CuriePME.setDistanceMode(Intel_PMT::PATTERN_MATCHING_DISTANCE_MODE::LSUP_Distance);
		Serial.println("Set the NN to LSUP Distance");
	}
	else
	{
		CuriePME.setDistanceMode(Intel_PMT::PATTERN_MATCHING_DISTANCE_MODE::L1_Distance);
		Serial.println("Set the NN to L1 Distance");
	}

	printDistanceMode();
}

static const int serialBAUD = 9600;

void setup()
{
//blah blah
Serial.begin(SerialBAUD);

	while (!Serial);
	
	delay(1000);
	
	CuriePME.begin();
}

void loop()
{
 toggleDistanceMode()
}

Calling the function setDistanceMode has no effect.

Marcus

**Comment by eriknyquist** [comment]
Fixed: https://github.com/01org/Intel-Pattern-Matching-Technology/pull/23

**Comment by marcusobrien** [comment]
I have verified this is fixed can now change the distance mode ...


Toggling the Distance Mode
Current Distance mode is LSUP
Set the NN to L1 Distance
Current Distance mode is L1
