### ISSUE TITLE
File Versions 

### ISSUE THREAD

**Issue by marcusobrien** [01org/Intel-Pattern-Matching-Technology#26]
Hi,

When doing a pull from one of the repo branches it is not possible to tell from looking at the source files which version one has. For example if I pull now, and a fix goes in, I have to look at my repo settings to ascertain if I have the fix. Is there any way the source files (.h and .cpp) can have a version Number of GUID in them ? At least it will be easy to see what version one has ? 

ie

#define VERSION 1.0

Every time a commit is done, up the version. Then at least the docs can cross-reference the source versions ie Fix for Bug 231 is fixed in version 1.01 etc,.

**Comment by eriknyquist** [comment]
Hi @marcusobrien, we've never done this with any of our other repos, as far as I know, but I'd be open to trying it. Can you help me understand how this gives us something that we don't already get with git?

**Comment by eriknyquist** [comment]
@marcusobrien the library will soon be merged with corelibs-arduino101, so it will be versioned along with that. Closing.
