### ISSUE TITLE
CurieIMU.accelDataReady() not a function

### ISSUE THREAD

**Issue by pvanallen** [01org/Intel-Pattern-Matching-Technology#30]
In Arduino IDE 1.8.1 and Intel Curie Boards 1.0.7, I get the following error in Drawing in the Air:

Arduino: 1.8.1 (Mac OS X), Board: "Arduino/Genuino 101"

/DrawingInTheAir.ino: In function ‘void readVectorFromIMU(byte*)’:
DrawingInTheAir:172: error: ‘class CurieIMUClass’ has no member named ‘accelDataReady’
         if (CurieIMU.accelDataReady()) {
                      ^
exit status 1
‘class CurieIMUClass’ has no member named ‘accelDataReady’

**Comment by eriknyquist** [comment]
@pvanallen yes, you need the latest code from https://github.com/01org/corelibs-arduino101 in order to use that example. We have not yet done a new release to Arduino.

**Comment by pvanallen** [comment]
@eriknyquist ah, okay. I didn't see accelDataReady in the CurieIMU/keywords.txt file, so I didn't bother trying to download that version. I worked around it by adding a delay(5) inside the readVectorFromIMU while loop to match the sample rate.
