### ISSUE TITLE
 'class CurieIMUClass' has no member named 'accelDataReady' 

### ISSUE THREAD

**Issue by xhuvom** [01org/Intel-Pattern-Matching-Technology#35]
@eriknyquist 
I'm trying to experiment with the Draw I the Air example but after installing the PME library on Arduino IDE, compiling shows the error on 
```
 while (digitalRead(buttonPin) == HIGH) {
        if (CurieIMU.accelDataReady()) {

            CurieIMU.readAccelerometer(raw[0], raw[1], raw[2]);
```

  **'class CurieIMUClass' has no member named 'accelDataReady'** 

Is that improper library installation?

**Comment by eriknyquist** [comment]
If you are using the CuriePME library, you will need to get the latest Curie boards package from Github, at 01org/corelibs-arduino101
